### ISSUE TITLE
NUMBER OF ITERATIONS NEEDED

### ISSUE THREAD

**Issue by cynthia-nohuje** [chiragbiradar/DDoS-Attack-Detection-and-Mitigation#21]
How many iterations are needed when generating the data in mininet using the command 'sudo python generate_benign_trafic.py'
 Please help

**Comment by harika1314** [comment]
Hey , If anyone finished the project , let me know I need your help

**Comment by chiragbiradar** [comment]
@cynthia-nohuje it depends on your ml model, for me to generate around 2667523 rows it took almost 3 days
