### ISSUE TITLE
Module version

### ISSUE THREAD

**Issue by Abacus-web** [chiragbiradar/DDoS-Attack-Detection-and-Mitigation#4]
hi, please i need more details on the version of pandas, scipy, numpy and scikit-learn used

**Comment by chiragbiradar** [comment]
Hello, you can use the latest versions of pandas, scipy, numpy and scikit-learn.

**Comment by Abacus-web** [comment]
Hi sir, I installed the latest versions but when i run the command "ryu-manager controller.py " I got the following error

 raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typeDict'

I tried to install different version of numpy but i still got the same error.

![Screenshot at 2023-01-16 22-33-16](https://user-images.githubusercontent.com/57025237/212768845-a1954e76-b0ef-436b-8cb6-0be1faf87d8e.png)

**Comment by chiragbiradar** [comment]
Kindly refer to our virtual machines located at the following link: [LINK](https://drive.google.com/drive/folders/1lqenExgjdaPsXrcH2PDfVOBZ5-QAKpVa) for resolution of any issues. If the problem persists, I would be delighted to provide further assistance.

**Comment by Jaliyakhcj** [comment]
Hi .. 
Could you please give the running steps of this project with small description
like below Example 
1. generate_benign_trafic.py  #  Mininet
2. start_traffic_collection.py   # RYU - to Collect traffic creating FlowStatsfile.csv file
3. generate_ddos_trafic.py     # Mininet
4.
5.
6.

 Please let me know the script names and what is dose for each step.

thx
Jaliya

**Comment by chiragbiradar** [comment]
@Jaliyakhcj 

Thank you for your interest in my project. Below are the running steps for the project with a brief description for each:

generate_benign_trafic.py - This script generates benign traffic using Mininet.
start_traffic_collection.py - This script uses RYU to collect traffic and creates a FlowStatsfile.csv file.
generate_ddos_trafic.py - This script generates DDoS traffic using Mininet.
Here are the steps you can follow to run the project:

Open RYU and note down the IP address of RYU using the "ifconfig" command.
Go to the project>controller folder path.
To generate the dataset, it takes about 2-3 days to generate the dataset, so it is recommended to use the given dataset. If you still want to generate a new dataset, go to Mininet then cd project/mininet and in generate_benign_trafic.py file, change the controller IP address to the RYU IP that you noted. Go back to RYU and run collect_ddos_trafic.py. The data generation and collection will be started.
Start the controller by running controller.py in RYU.
Go to Mininet and start topology.py, and change the controller IP.
Use the following attack command in Mininet: "h1 hping3 -1 -V -d 120 -w 64 -p 80 --rand-source --flood h12" where h1 is attacking h12 using ICMP flood. You can use other attacks as well.
Check in the controller whether the attack is detected and mitigated.
I hope these steps will be helpful to you. Please let me know if you have any further questions or concerns.

Thank you for your time and consideration. I would greatly appreciate it if you could give my project a start.

Best regards,
@chiragbiradar

**Comment by MOHassan95** [comment]
It's my first time use this project can u plz give me command for each command I know I will tried you but I need it the you for your effort.

**Comment by chiragbiradar** [comment]
https://github.com/chiragbiradar/DDoS-Attack-Detection-and-Mitigation/issues/5
https://github.com/chiragbiradar/DDoS-Attack-Detection-and-Mitigation/tree/main/Installation_setup
check this out

**Comment by MOHassan95** [comment]
Thx you for help I want to connect you in email if you want I want to ask you ?

**Comment by viettd14** [comment]
> Kindly refer to our virtual machines located at the following link: [LINK](https://drive.google.com/drive/folders/1lqenExgjdaPsXrcH2PDfVOBZ5-QAKpVa) for resolution of any issues. If the problem persists, I would be delighted to provide further assistance.

i am researching on ddos sdn topic, i have imported your ova file into virtual box, can you give me root pass of VM: ryu-controller and mininet

**Comment by chiragbiradar** [comment]
ryu-controller -> ryu
mininet -mininet

**Comment by Marvelous-coco** [comment]
hello, I have run the hping3 command to launch ICMP flood,  and I can capture ICMP packets on ryu manager 's wireshark, how can I know whether the ryu manager detected or mitigated the DDos attack?

**Comment by chiragbiradar** [comment]
To determine whether the Ryu manager detected or mitigated the DDoS attack, you can follow these steps:

1. **Packet Flow Behavior**:
   - Observe the packet flow behavior within the Ryu controller. You can analyze how the controller processes incoming packets, identifies anomalies, and responds to potential attacks.
   - Look for any abnormal patterns, such as a sudden surge in ICMP traffic or unusual packet rates. If the Ryu controller has implemented specific rules or algorithms for DDoS detection, it should exhibit different behavior during an attack.

2. **Mininet Terminal**:
   - Mininet program displays whether attack is attack is being detected or mitigated.(there are separate scripts for both)
