### ISSUE TITLE
Steps to Perform

### ISSUE THREAD

**Issue by Dekryptxr** [chiragbiradar/DDoS-Attack-Detection-and-Mitigation#5]
Step-1 install [Virtual box](https://www.virtualbox.org/wiki/Downloads) or VM-ware workstation (Virtual box preffered)
Step-2 install [Mininet-VM](https://github.com/mininet/mininet/releases/)
Step-3 install [Ubuntu](https://ubuntu.com/download/desktop) in virtual box
Step-4 install [ryu-controller](https://ryu.readthedocs.io/en/latest/getting_started.html) in ubuntu vm
Step-5 Use git clone to install the code files

git clone https://github.com/chiragbiradar/DDoS-Attack-Detection-and-Mitigation-using-Machine-Learning.git

NOTE: You can download MininetVM and Ubuntu with pre-installed Ryu from here: https://drive.google.com/drive/folders/1lqenExgjdaPsXrcH2PDfVOBZ5-QAKpVa

If you’ve download the vm’s  from our provided link: Login id and password for mininet is “mininet” and for Ubuntu is “ryu”
Open both the virtual machines side by side: 

Commands for Ubuntu
STEP 1.  Do “ifconfig” and copy the ipaddress.
STEP 2. Navigate to “controller” directory.
STEP 3.  Turn on ryu-controller with the command: “ryu-manager KNN_Controller.py” and then go to MininetVM

Commands for Mininet
STEP 1. Navigate to the “mininet” folder.
STEP 2. 	Edit topology.py with “nano topology.py” now go to the last section and replace the ip address with Victim’s ip address then save and exit.
STEP 3. Now activate mininet with “sudo python topology.py” (check your python version if its 3 then do “python3”)
Step 4. 	Test if your system is working with commands like “h1 ping h3” if you don’t have hping3 installed then install it with the following command “sudo apt-get install hping3” 
Step 5: You can also test the system with “pingall”
Step 6: start the Attack, these are the following  commands:
Icmp flood command: hping3 -1 -V -d 120 -w 64 -p 80 --rand-source –flood
SYN flood command: hping3 -S -V -d 120 -w 64 -p 80 --rand-source --flood 
Udp flood command: hping3 -2 -V -d 120 -w 64 -p 80 --rand-source –flood
You can give anyone of these 3
And use these commands like if you want to perform attack from h2 host to h10 host then:
h1 hping3 -1 -V -d 120 -w 64 -p 80 --rand-source --flood h2
here you can change hosts as you like

Now you will see in the Ubuntu VM that the attack is detected and mitigated.

Now what you just performed is a DOS attack, to make it DDOS you can create different instances of Mininet or you can use two different machine to perform or you can use remote ssh server

**Comment by Shashanka-G** [comment]
![image](https://github.com/chiragbiradar/DDoS-Attack-Detection-and-Mitigation/assets/84120698/81cb91e7-bba8-41d1-8657-0f9a49b1ec55)

For step 2 do i need to modify controllers ip address?

**Comment by chiragbiradar** [comment]
Yes @Shashanka-G

**Comment by cynthia-nohuje** [comment]
Unable to contact the remote controller at 10.0.2.101:6653

**Comment by cynthia-nohuje** [comment]
please help me with this error

![Screenshot 2024-04-08 104625](https://github.com/chiragbiradar/DDoS-Attack-Detection-and-Mitigation/assets/117440038/1dd3c804-a5f0-4976-8548-0af1128d50b7)

**Comment by chiragbiradar** [comment]
@cynthia-nohuje try using VM images provided in the repo

**Comment by cynthia-nohuje** [comment]
Hie sir please help me , after i have downloaded and imported the VMs
provided in the repo my ethernet stopped working  .


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by cynthia-nohuje** [comment]
![ryu error](https://github.com/chiragbiradar/DDoS-Attack-Detection-and-Mitigation/assets/117440038/b26e8e52-5f29-4b5f-9804-07945e7ea345)
when using the vms povided thats the error im getting somebody help
